### PR TITLE
Nonce update with seconds sometimes to slow

### PR DESCRIPTION
**Pull request by FerrySchuller**
Fixed with int(time.time()*1000)

### CODE REVIEW

**Comment by s4w3d0ff** [comment]
I don't understand, if you are running the `Poloniex.api()` method __linearly__ (_not in parallel_) the 'nonce' should never fall behind... Be sure you aren't threading the method. If you are, you may need to add a lock or uses multiple api keys so the nonces don't overlap/fall behind.

**Comment by svendsen** [comment]
Change is needed, but it should be enough to multiply with 6.
Nonce is initialized to int(time.time()) with is seconds since the eponch. Poloniex allows for a maximum of 6 calls per seconds. Thus, the nonce variable can increase at most 6 times per second. If you imagine that you run you an implementation for one minute with a constant 6 calls per seconds, nonce will increase by 60 * 6 = 3600 during that one minute. But if you then restart your program, nonce will be initialized to seconds since epoch, thus 60 higher than in the last run, giving you a nonce value lower than the nonce of final poloniex command in previous run (3600 - 60 = 3540 too low, to be precise).

**Comment by s4w3d0ff** [comment]
thanks @svendsen for the breakdown. So this is really only a issue if the Poloniex instance has to be re-initialized over and over quickly?

Not sure why you would NEED to do such a thing. If it is because a script keeps restarting (un-godly fast), then what I mentioned above (defining the nonce manualy after 'init') should work.

Otherwise move the `polo=Poloniex()` out of whatever loop is initializing the object over and over...:
```python
polo = Poloniex()
for i in range(6*4):
    print(polo.marketTicker()['BTC_ETH'])
# or
polo = Poloniex(coach=True)
for i in range(6*4):
    print(polo.marketTicker()['BTC_ETH'])

# NOT THIS:
for i in range(6*4):
    polo = Poloniex()
    print(polo.marketTicker()['BTC_ETH'])
```
I still dont understand how this can be an issue unless the module is being used 'incorrectly' or your program is still in development (so adding 1 line `polo.nonce = polo.nonce*1000` would probably be best).

If I am wrong let me know, I'll merge the branch (it won't hurt anyone).

**Comment by svendsen** [comment]
@s4w3d0ff Maybe I have misunderstood this, but as I understand it, Poloniex always expects an increasing nonce, even when the Poloniex instance is reinitialized (when restarting your script). If this is true, any program with a call frequency higher than once per second will encounter the problem when it restarts: The nonce value will be initialized to a lower value than the nonce value of the last call, because it is initialized by a value that by definition only increases once per second. The script nonce gets "ahead" of the timer value (increasing once per second) because it calls, this increases, more than once per second. Hope this makes sense.

**Comment by s4w3d0ff** [comment]
Totally makes sense, thanks. I guess my internet is too slow to properly test this but I merged the commit. My derp :d

**Comment by s4w3d0ff** [comment]
Just to claify:
__Before Commit__:
Poloniex object initialized
time = 1473102891.645123
nonce = 1473102891
make call x6 before 1473102892
nonce = 1473102896 (sent to poloniex.com)
Poloniex object re-initialized
time = 1473102892.645123
nonce = 1473102892
^^^ nonce too low!

__After Commit__:
Poloniex object initialized
time = 1473102891.645123
nonce = 1473102891645
make call x6 before 1473102892
nonce = 1473102891651 (sent to poloniex.com)
Poloniex object re-initialized
time = 1473102892.645123
nonce = 1473102892645
^^^ nonce OK

So now the only time the nonce can be slow is if someone is making 1000+ requests a sec (which I doubt Poloniex would approve) and re-initalizing the object.

**Pull request merged**
