### PR TITLE
fix time calc bug

### PR DESCRIPTION
**Pull request by s4w3d0ff**
The old coach(s) were sending out 6 requests in 'bulk' every second
While this is successfully restricting the calls, it is not as 'smooth' as I would like it. This PR fixes the issue and each request is now being properly spaced rather than waiting 1 seccond, then sending 6 requests...

### CODE REVIEW

**Comment by enricobacis** [comment]
Uhm.. this makes no sense to me, if you want your application to space out requests add a sleep in your specific code. But for an API client, you should allow people to throw requests as soon as they can.

**Comment by s4w3d0ff** [comment]
You are right, my explaination is not very good. I was noticing that the coach was acting differently than the original. After a brief test I noticed that the coach was releasing API request in groups of 6. Thinking this was a bug I tried to 'fix' it and only made things worst. Turns out that it is normal behavior for the coach and after testing with random sleep times (simulating random API calls) the 'bug' was gone for all 3 versions of the coach.

The issue I have now with Coach3 (your version) is that it seems the first 5 API calls are all waiting 1 sec even if it does not need to wait. The first 5 calls should never need to wait. From my understanding, every API call is waiting 1 sec but in a thread... I don't see how this  creates the correct time gap without calculating the required wait time.

The version I came up with uses both a semaphore and a deque, calulating the correct wait time. It no longer uses a Timer but it can be added quite easily.

**Comment by enricobacis** [comment]
Your understanding is correct, at the beginning you create a semaphore, it's like a shop with 6 cashiers, all without clients.

|   |   |   |   |   |   |
|---|---|---|---|---|---|

When the first client arrives, it takes the first free cashier. The serving time is 1 second, so we block the cashier for one second

| 1.0s |   |   |   |   |   |
|------|---|---|---|---|---|

Assume that another client arrives after 0.3s, the first cashier is still unavailable for 0.7s, but there are still empty slots, so the client is server by the second cashier.

| 0.7s | 1.0s |   |   |   |   |
|------|---|---|---|---|---|

And so on.

## Proof of correctness

the worst case is an infinite queue of clients waiting to be served. You instantly reach this situation:

| 1.0s | 1.0s | 1.0s | 1.0s | 1.0s | 1.0s |
|------|---|---|---|---|---|

So the first 6 clients do not wait, then the serving process last 1 second for all of them

| 0.9s | 0.9s | 0.9s | 0.9s | 0.9s | 0.9s |
|------|---|---|---|---|---|

| 0.8s | 0.8s | 0.8s | 0.8s | 0.8s | 0.8s |
|------|---|---|---|---|---|

.....

| 0.2s | 0.2s | 0.2s | 0.2s | 0.2s | 0.2s |
|------|---|---|---|---|---|

| 0.1s | 0.1s | 0.1s | 0.1s | 0.1s | 0.1s |
|------|---|---|---|---|---|

Then all the 6 clients are served, so the semaphore is emptied

|   |   |   |   |   |   |
|---|---|---|---|---|---|

but as soon as it empties, it is refilled with other waiting clients

| 1.0s | 1.0s | 1.0s | 1.0s | 1.0s | 1.0s |
|------|---|---|---|---|---|

This means that you have served 6 clients in one second, than other 6 clients in another second.
The result is that it doesn't matter when your actual second starts, but if you take a time delta of 1 second, you cannot have more than 6 clients server (which is actually what you want).

**Comment by s4w3d0ff** [comment]
But the first clients to the cashiers are still waiting 1 sec  before released. So if I make a single API call the coach will make it wait a full second before executing.

Like I said, it does do as advertised and restrict the call limit, but every call is waiting 1 sec rather than the minimum wait time, which is fine if you don't mind a 1 second delay in your first 6 calls.

**Comment by enricobacis** [comment]
Not really, because the `Timer` is the stuff that keeps the cashier busy and the timer is executed in another thread (which actually just performs `sleep(seconds)` and `semaphore.release()`), but the `semaphore.acquire()` method is non blocking if a cashier is available.

Actually there is something bad about your code, which is the following. It start counting before the call, so for example if the network goes down 1 second, every implementation of your Coach is going to throw 2 times the allowed invocation in a burst when the network becomes available. You should wait before the method and then count 1 second after the method ends.

Check out the implementation of https://github.com/enricobacis/limit

**Comment by s4w3d0ff** [comment]
I still don't really understand why you need to wait 1 sec for the first 6 calls but after some brief testing it seems I am wrong and the first 6 calls _do_ execute immediately and your version of the coach is the fastest of the 3 to handle 6 commands:

```python
coach = Coach()
start = time()
for i in range(6):
    coach.wait()
end = time()
print('coach', end - start)
coach = Coach2()
start = time()
for i in range(6):
    coach.wait()
end = time()
print('coach2', end - start)
coach = Coach3()
start = time()
for i in range(6):
    coach.wait()
end = time()
print('coach3', end - start)
```
```
('coach', 1.001150131225586)
('coach2', 1.001194953918457)
('coach3', 0.0050699710845947266)

```

**Comment by enricobacis** [comment]
In fact I don't need to wait, the cashier have a spare 1 second after
serving a client, so she puts a timer that turn the green light on after
one second

**Comment by s4w3d0ff** [comment]
OK, I think I get it... It is because the semaphore is being released in a thread, this allows the coach to continue working while still holding the semaphore. And since each cashier takes a 1 sec break after being called (still holding a semaphore), you can never go beyond the call limit.

**Comment by enricobacis** [comment]
Exactly!

**Pull request merged**
